### ISSUE TITLE
Refactor trace in auditlog

### ISSUE THREAD

**Issue by henomis** [henomis/mailqueue-go#18]
**Is your feature request related to a problem? Please describe.**
`Tracer` is bad name for this package and it should be moved in `internal/pkg/auditlog`

**Describe the solution you'd like**
Refactor `Tracer` and move to right position

**Tasks**
- [x] Refactor `Tracer` https://github.com/henomis/mailqueue-go/pull/19
- [x] Change `Trace` in `Log` https://github.com/henomis/mailqueue-go/pull/20
- [x] Switch to `auditlog` https://github.com/henomis/mailqueue-go/pull/21

**Comment by henomis** [comment]
done
